source-code/code/studyup/discussion/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, RadioField, SelectMultipleField, TextAreaField
from wtforms.widgets import ListWidget, CheckboxInput, TextArea
from wtforms.validators import DataRequired

class CommentForm(FlaskForm):
    body = TextAreaField('Comment', validators=[DataRequired()], widget=TextArea())
    submit = SubmitField('Comment')

source-code/code/studyup/dashboard/__init__.py
#ignore this

source-code/code/studyup/dashboard/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, abort
from studyup import db
from studyup.main.routes import index
from studyup.models import User, Question, Choice, Answer, Comment
from flask_login import current_user, login_required

dashboard = Blueprint('dashboard', __name__)

@dashboard.route("/dashboard", methods=['GET', 'POST'])
@login_required
def mod_dashboard():
	if current_user.user_type != 2: ## if not moderator
		abort(403)
	users = User.query.all()
	questions = Question.query.all()
	choices = Choice.query.all()
	answers = Answer.query.all()
	comments = Comment.query.all()
	return render_template('dashboard.html', users=users, questions=questions, choices=choices, answers=answers, comments=comments)


@dashboard.route("/delete-user/<int:user_id>", methods=['GET', 'POST'])
@login_required
def delete_user(user_id):
	if current_user.user_type != 2: ## if not moderator
		abort(403)
	user = User.query.filter_by(id=user_id).first()
	comments = Comment.query.filter_by(user_id=user_id).all()

	for comment in comments:
		db.session.delete(comment)
	db.session.delete(user)
	db.session.commit()
	flash('User has been deleted!', 'success')


	return redirect(url_for('dashboard.mod_dashboard'))

@dashboard.route("/delete-question/<int:q_id>", methods=['GET', 'POST'])
@login_required
def delete_question(q_id):
	if current_user.user_type != 2: ## if not moderator
		abort(403)
	question = Question.query.filter_by(id=q_id).first()
	comments = Comment.query.filter_by(user_id=q_id).all()

	for comment in comments:
		db.session.delete(comment)
	db.session.delete(question)
	db.session.commit()
	flash('Question has been deleted!', 'success')


	return redirect(url_for('dashboard.mod_dashboard'))

@dashboard.route("/reset", methods=['GET', 'POST'])
@login_required
def reset():
	if current_user.user_type != 2: ## if not moderator
		abort(403)
	User.query.delete()
	Question.query.delete()
	Choice.query.delete()
	Answer.query.delete()
	Comment.query.delete()
	db.session.commit()
	return render_template('index.html')

source-code/code/studyup/discussion/routes.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, flash, abort
from studyup.models import Question, Choice, Answer, Comment, User
from studyup import db
from studyup.discussion.forms import CommentForm
from flask_login import login_required, current_user
from datetime import datetime

discussion = Blueprint('discussion', __name__)
comment = Blueprint('comment', __name__)

#returns topic name of given topicNo
@discussion.route("/api/topic/<int:topic_no>")
def topic(topic_no):
    TOPICS = [
        (1, 1, 1, 'Standards and units, Unit consistency, Uncertainty and significant figures'),
        (1, 1, 2, 'Vectors and vector addition, Components of vectors, Unit vectors'),
        (1, 2, 3, 'Displacement, time, and average velocity, Instantaneous velocity'),
        (1, 2, 4, 'Average and instantaneous acceleration'),
        (1, 2, 5, 'Motion with constant acceleration, Freely falling bodies'),
        (1, 3, 6, 'Position and velocity vectors, Acceleration vector'),
        (1, 3, 7, 'Projectile motion'),
        (1, 3, 8, 'Motion in a circle'),
        (1, 3, 9, 'Relative velocity'),
        (1, 4, 10, 'Force and interactions, Mass and weight, Newton\'s first law, Inertial frames of reference'),
        (1, 4, 11, 'Free-body diagrams, Newton\'s second law, Newton\'s third law'),
        (1, 5, 12, 'Newton\'s 1st law: particles in equilibrium'),
        (1, 5, 13, 'Newton\'s 2nd law: dynamics of particles'),
        (1, 5, 14, 'Frictional forces'),
        (1, 5, 15, 'Dynamics of circular motion'),
        (2, 6, 16, 'Scalar product, Work'),
        (2, 6, 17, 'Work and kinetic energy'),
        (2, 6, 18, 'Work and energy with varying forces, Power'),
        (2, 7, 19, 'Gravitational potential energy, Conservation of mechanical energy (gravitational force), Conservative and nonconservative forces'),
        (2, 7, 20, 'Elastic potential energy, Conservation of mechanical energy'),
        (2, 7, 21, 'Force and potential energy, Energy diagrams'),
        (2, 8, 22, 'Momentum and Impulse'),
        (2, 8, 23, 'Conservation of momentum, Momentum conservation and collisions'),
        (2, 8, 24, 'Elastic collisions'),
        (2, 8, 25, 'Center of mass'),
        (2, 9, 26, 'Angular velocity and acceleration, Rotation with constant angular acceleration'),
        (2, 9, 27, 'Relating linear and angular kinematics'),
        (2, 9, 28, 'Energy in rotational motion, Parallel-axis theorem'),
        (2, 10, 29, 'Vector product, Torque'),
        (2, 10, 30, 'Torque and Angular acceleration for a rigid body'),
        (2, 10, 31, 'Rigid-body rotation about a moving axis'),
        (2, 10, 32, 'Angular momentum, Conservation of angular momentum'),
        (3, 11, 33, 'Conditions for equilibrium, Center of gravity'),
        (3, 11, 34, 'Solving rigid-body equilibrium problems'),
        (3, 11, 35, 'Stress, strain, elastic moduli, Elasticity and plasticity'),
        (3, 12, 36, 'Density, Pressure in a fluid'),
        (3, 12, 37, 'Buoyancy'),
        (3, 12, 38, 'Fluid flow, Bernoulli\'s equation'),
        (3, 13, 39, 'Newton\'s law of gravitation, Weight'),
        (3, 13, 40, 'Gravitational potential energy, Motion of satellites'),
        (3, 13, 41, 'Kepler\'s laws and the motion of the planets'),
        (3, 14, 42, 'Describing oscillation, Simple harmonic motion'),
        (3, 14, 43, 'Energy in simple harmonic motion'),
        (3, 14, 44, 'Applications of simple harmonic motion, The simple pendulum, The physical pendulum'),
        (3, 14, 45, 'Damped Oscillations, Forced Oscillations'),
        (3, 15, 46, 'Types of mechanical waves, Periodic waves, Mathematical description of wave, Speed of a transverse wave'),
        (3, 15, 47, 'Energy in wave motion, Wave interference, boundary conditions, and superposition'),
        (3, 15, 48, 'Standing waves on a string, Normal modes of a string'),
        (3, 16, 49, 'Doppler Effect')
            ]

    return jsonify({'name': TOPICS[topic_no - 1][3]})


@discussion.route("/api/topic/<int:topic_num>/questions")
def questionPerTopic(topic_num):
    q = Question.query.filter_by(topic_no=int(topic_num)).all()

    qList = []
    for question in q:
        questionObj = {}
        questionObj['id'] = question.id
        questionObj['body'] = question.body
        qList.append(questionObj)
    return jsonify({'questions': qList})

@discussion.route('/discussion')
def select():
    return render_template('discussion.html')

@discussion.route('/discussion/<int:question_id>', methods=['GET','POST'])
@login_required
def add_comment(question_id):
    form = CommentForm()
    question = Question.query.filter_by(id=question_id).first()
    if form.validate_on_submit():
        comment = Comment()
        comment.time_posted = datetime.utcnow()
        comment.comment = form.body.data
        user = User.query.filter_by(username=current_user.username).first()
        comment.user_id = user.id
        comment.question_id = question_id 
        db.session.add(comment)
        db.session.commit()
        flash('Comment added!', 'success')
        comments = Comment.query.filter_by(question_id=question_id).all()
        return redirect(url_for('discussion.add_comment', question_id=question_id, comments=comments, tempRemove=0))

    comments = Comment.query.filter_by(question_id=question_id).all()
    return render_template('view-question.html', form=form, question=question, comments=comments, tempRemove=0)

@discussion.route('/discussion/<int:question_id>/edit/<int:comment_id>', methods=['GET','POST'])
@login_required
def edit_comment(question_id, comment_id):
    question = Question.query.filter_by(id=question_id).first()
    comments = Comment.query.filter_by(question_id=question_id).all()
    comment = Comment.query.filter_by(id=comment_id).first()
    form = CommentForm()
    if comment.user != current_user:
        abort(403)
    if form.validate_on_submit():
        comment.comment = form.body.data
        comment.edited = True
        db.session.commit()
        flash('Comment edited', 'success')
        return redirect(url_for('discussion.add_comment', question_id=question_id, comments=comments, tempRemove=0))
    return render_template('view-question.html', question=question, form=form, comments=comments, tempRemove=comment_id, editComment=comment)

@discussion.route('/discussion/<int:question_id>/delete/<int:comment_id>', methods=['POST'])
@login_required
def delete_comment(question_id,comment_id):
    # question = Question.query.filter_by(id=question_id).first()
    comments = Comment.query.filter_by(question_id=question_id).all()
    comment = Comment.query.filter_by(id=comment_id).first()
    if current_user.user_type != 2: # not a moderator 
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment has been deleted!', 'success')
    return redirect(url_for('discussion.add_comment',question_id=question_id, comments=comments))

source-code/code/studyup/main/routes.py
"""
LICENSE
This is a course requirement for CS 192 Software Engineering II 
under the supervision of Asst. Prof. Ma. Rowena C. Solamo 
of the Department of Computer Science, College of Engineering, 
University of the Philippines, Diliman for the AY 2019-2020
AUTHORS: Ang, Karina Kylle L. 
         Kopio, Katrina Mae D. 
         Principio, Roberto Jr. D.

CODE HISTORY
01-23-2020 Principio - File created, code added, documentation added

INFO
File Creation Date: January 24, 2020
Development Group: Group 9 - StudyUP Team
Client Group: Ma'am Solamo, CS 192 Class
Purpose of the Software: To provide a collaborative learning
    environment in the courses of UP Diliman.
"""

from flask import Blueprint, render_template, request
from studyup.models import Question, Choice, Answer, User, Comment
from studyup import db

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/index")
def index():
    return render_template('index.html')

source-code/code/studyup/question/__init__.py
#ignore this too

source-code/code/studyup/user/routes.py
import secrets, os
from PIL import Image
from flask import Blueprint, render_template, flash, redirect, url_for, request
from studyup import db, bcrypt
from studyup.user.forms import RegistrationForm, LoginForm, UpdateAccountForm
from studyup.main.routes import index
from studyup.models import User
from sqlalchemy import func
from flask_login import login_user, current_user, logout_user, login_required

user = Blueprint('user', __name__)

@user.route("/register", methods=['GET','POST'])
def register():
	form = RegistrationForm()
	if current_user.is_authenticated:
		return redirect(url_for('main.index')) #should go to index
	if form.validate_on_submit():
		hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User()
		user.username=form.username.data
		user.email = form.email.data
		user.password = hashed_pw
		if (form.usertype.data == 's'):
			user.user_type = 1
		else:
			user.user_type = 2
		db.session.add(user)
		db.session.commit()
		flash('Your account has been successfully created!', 'success')
		return redirect(url_for('user.login')) 
	return render_template('register.html', title='Register', form=form)


@user.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.index'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.index'))
			flash('Login Successful. Welcome!')
			return redirect(url_for('main.index'))
		else:
			flash('Login Unsuccessful. Please check email and password', 'danger')
	return render_template('login.html', title='Login', form=form)

@user.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))

def save_picture(form_picture):
	#randomize name of image
	random_hex = secrets.token_hex(8)
	#renaming uploaded filename and save to folder
	_, f_ext = os.path.splitext(form_picture.filename)
	picture_fn = random_hex + f_ext
	picture_path = os.path.join(user.root_path, '../static/img/user', picture_fn)

	output_size = (125, 125)
	img = Image.open(form_picture)
	img.thumbnail(output_size)
	img.save(picture_path)

	return picture_fn

@user.route("/account", methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		#updating profile picture
		if form.picture.data:
			picture_file = save_picture(form.picture.data)
			current_user.image_file = picture_file
		#updating username and email
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Your account has been updated', 'success')
		return redirect(url_for('user.account'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
	image_file = url_for('static', filename=f'img/user/{current_user.image_file}')
	return render_template('account.html', title='Account', image_file=image_file, form=form)

source-code/code/studyup/templates/account.html
{% extends 'base.html' %}

{% block title %}
StudyUP | Account
{% endblock title %}


{% block body %}
	<div class="content-section">
		<div class="media">
		<img class="rounded-circle account-img pic-profile" src="{{ image_file }}">
		<div class="media-body">
			<h2 class="account-heading">{{ current_user.username }}</h2>
			<p class="text-secondary">{{ current_user.email }}</p>
		</div>
		</div>
		<div class="content-section">
			<form method="POST" action="" enctype="multipart/form-data"> 
				{{ form.hidden_tag() }}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Account Info: 
						{% if current_user.user_type == 1 %}
							Student
						{% else %}
							Moderator
						{% endif %}
					</legend>
					<div class="form-group">
						{{ form.username.label(class="form-control-label") }}
	
						{% if form.username.errors %}
							{{ form.username(class="form-control form-control-lg is-invalid") }}
							<div class="invalid-feedback">
								{% for error in form.username.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.username(class="form-control form-control-lg") }}
						{% endif %}
					</div>
					<div class="form-group">
						{{ form.email.label(class="form-control-label") }}
						{% if form.email.errors %}
							{{ form.email(class="form-control form-control-lg is-invalid") }}
							<div class="invalid-feedback">
								{% for error in form.email.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.email(class="form-control form-control-lg") }}
						{% endif %}
					</div>
					<div class="form-group">
						{{ form.picture.label() }}
						{{ form.picture(class="form-control-file") }}
						{% if form.picture.errors %}
							{% for error in form.picture.errors %}
								<span class="text-danger">{{ error }}</span></br>
							{% endfor %}
						{% endif %}
					</div>	
				</fieldset>
				<div class="form-group">
					{{ form.submit(class="btn btn-outline-info") }}
				</div>
			</form>
		</div>
	</div>
{% endblock body %}

source-code/code/studyup/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">
    <title>
        {% block title %}
        
        {% endblock title %}
    </title>
</head>
<body>
    
<nav class="navbar navbar-expand-md navbar-custom sticky ztop">
    <a href="/" class="navbar-brand click-exit" name="btn-home"><strong>StudyUP</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar7">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-stretch" id="navbar7">
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}

            {% if current_user. user_type == 2 %}

            <li class="nav-item">
              <a name="btn-dashboard" class="nav-link" href="{{url_for('dashboard.mod_dashboard')}}"><strong>Dashboard</strong></a>
           </li>

            <li class="nav-item">
                <a name="btn-question" class="nav-link" href="{{url_for('question.create_question')}}"><strong>Create Question</strong></a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a name="btn-practice" class="nav-link click-exit" href="{{url_for('practice.select')}}"><strong>Practice</strong></a>
            </li>
            <li class="nav-item">
                <a name="btn-discuss" class="nav-link click-exit" href="{{url_for('discussion.select')}}"><strong>Discuss</strong></a>
            </li>
              <li class="nav-item">
                <a name="btn-account" class="nav-link click-exit" href="{{url_for('user.account')}}"><strong>Account</strong></a>
              </li>
              <li class="nav-item">
                <a name="btn-account" class="nav-link click-exit" href="{{url_for('user.logout')}}"><strong>Logout</strong></a>
              </li>
            {% else%}
              <li class="nav-item">
                  <a name="btn-account" class="nav-link click-exit" href="{{url_for('user.login')}}"><strong>Login</strong></a>
              </li>
              <li class="nav-item">
                <a name="btn-account" class="nav-link click-exit" href="{{url_for('user.register')}}"><strong>Register</strong></a>
              </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}
{% block body %}
{% endblock body %}
</div>


<div class="mb-5"></div>

<footer class="page-footer font-small footer-bg pt-4">

  
    <div class="container-fluid text-center text-md-left">
  
    
      <div class="row">
  
        
        <div class="col-md-6 mt-md-0 mt-3">
  
        
          <h5 class="text-uppercase">About</h5>
          <p>StudyUP is a web application made by UP students for UP students.</p>
          <p>Our main goal is to foster a collaborative learning environment</p>
  
        </div>
       
  
        <hr class="clearfix w-100 d-md-none pb-3">
  
     
        <div class="col-md-3 mb-md-0 mb-3">
  
        
          <h5 class="text-uppercase">Links</h5>
  
          <ul class="list-unstyled footer-link">
            <li>
              <a name="btn-practice" class="click-exit btn-link" href="{{url_for('practice.select')}}">Practice</a>
            </li>
            <li>
              <a class="click-exit btn-link" href="{{url_for('discussion.select')}}">Discuss</a>
            </li>
            <li>
              <a class="click-exit btn-link" href="{{url_for('user.register')}}">Register</a>
            </li>
            <li>
              <a class="click-exit btn-link" href="{{url_for('user.login')}}">Login</a>
            </li>
          </ul>
  
        </div>

        <div class="col-md-3 mb-md-0 mb-3">
        Thank you!
        </div>
      </div>

    </div>
    <div class="footer-copyright text-center py-3">© 2020 Copyright: StudyUP
    </div>
</footer>
   

{% block scripts %}

{% endblock scripts %}


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="{{url_for('static', filename='js/jquery-3.4.1.min.js')}}"></script>
<script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
</body>
</html>

source-code/code/studyup/templates/index.html
{% extends 'base.html' %}

{% block title %}
StudyUP | Home
{% endblock title %}

{% block body %}
<h1>Home</h1>
<div class="space">

</div>
{% endblock body %}

source-code/code/studyup/templates/login.html
{% extends 'base.html' %}

{% block title %}
StudyUP | Create Question
{% endblock title %}


{% block body %}
	<div class="content-section">
		<!-- action="" will post info to same route -->
		<form method="POST" action=""> 
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
				</div>
				<div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
		</form>
	</div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('user.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock body %}

source-code/code/studyup/templates/view-question.html
{% extends 'base.html' %}

{% block title %}
StudyUP | Discussion
{% endblock title %}

{% block body %}

<div class="row">
    <div class="col-2"></div>
    <div class="col-8">
        <p id="topic-header" class="mt-3 text-muted"></p>
        <div class="shadow-sm card mt-3 px-3">
            <div class="card-body">
                <div class="card-title"><h5 class="mb-4"> {{ question.body }} </h5></div>
            </div>

                {% if editComment %}
                  <p id="editComment" class="hideRadioBtn"> {{ editComment.comment }} </p> 
                {% endif %}

                {% if question.image_file %}
                <div> <img src="{{ url_for('static', filename='img/' + question.image_file) }}" alt="" style="max-width:100%;"> </div>
                {% endif %}

            <div class="card-text">
                <div class="form-group">
                    {% for i in range(4) %}
                        <div class="form-group mb-2">
                            
                            <label id="fc-{{i}}">></label> 
                        </div>
                        
                    {% endfor %}
                </div>
            </div>

            
        </div>
    
    
    <div class="shadow-sm card mt-5 mx-auto">
        
        <div class="comment-thread">
            <div class="border-top mt-4 mb-2 my-3 ml-5 mr-5"></div>

            {% if comments %}
                {% for comment in comments %}

                
                {% if tempRemove == comment.id %}
                
                {% else %}
                
                <div class="comment-div ml-5 mr-5">
                    <div class="d-flex">
                        <div class="profile-picture mx-3">
                            <img src="{{ url_for('static', filename='img/user/' + comment.user.image_file) }}" alt="" class="pic-ico">
                        </div>
                        <div class="comment-text">
                            <div class="comment-header d-sm-flex justify-content-between h-25 mb-1">
                                <div>
                                <strong>{{comment.user.username}}</strong>
                                {% if comment.user.user_type == 1 %}
                                    <span class="badge badge-pill badge-secondary">Student</span>
                                {% else %}
                                <span class="badge badge-pill badge-primary">Moderator</span>
                                {% endif %}
                                </div>

                                <div>
                                <p class=" text-sm-center text-muted"> <small>{{comment.time_posted.strftime('%d %b %y')}}
                                {% if comment.edited == True %}
                                    (edited)
                                {% endif %}</small>
                                </p>
                                </div>

                                    
                                

                            </div>    
                            
                        
                        <div>
                            <p class="comment"> {{comment.comment}} </p>
                        </div>

                        <div>
                            {% if current_user.id == comment.user.id %}
                                    <a href="{{ url_for('discussion.edit_comment', question_id=question.id, comment_id=comment.id) }}">Edit</a>
                            {% endif %}

                            {% if current_user.user_type == 2 %}
                                    <button type="button" class="btn btn-danger btn-sm m-1 btnDelete" value={{comment.id}} data-toggle="modal" data-target="#deleteModal">Flag</button>
                            {% endif %}

                        </div>

                        </div>
                    </div>
                    <div class="border-top mt-2 mb-3"></div>
                </div>


                {% endif %}

                
                {% endfor %}
            {% else %}
            <div class="d-flex justify-content-center">
            <p class="text-muted">No comments yet.</p>
            </div>
            {% endif %}
            
            

           
            

            
        </div>
        
        <form action="" method="post">
        {{ form.csrf_token }}
        <div class="form d-flex justify-content-center">

            {% if tempRemove != 0 %}
            {{ form.body(id="comment-box", rows="4", cols="70", class="form-control ml-5 mr-5") }}
            {% else %}
            {{ form.body(rows="4", cols="70", class="form-control ml-5 mr-5", placeholder="Add a comment") }}
            {% endif %}


            
        </div>
            <div class="d-flex justify-content-end mt-3 mr-5">
            {{ form.submit(class="btn btn-outline-primary") }}
            </div>
        </form>
    
    <div class="mb-3"></div>
        
    </div>
    
        
    </div>
    <div class="col-2"></div>

</div>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Comment?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form id="modalDeleteForm" action="{{ url_for('discussion.delete_comment', question_id=question.id,comment_id=0) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
        </form>
        </div>
    </div>
    </div>
</div>




{% endblock body %}

{% block scripts %}

<script>

//IIFE for loading choices of each question as well as changing name attr of each form


(function() {
'use strict';
window.addEventListener('load', function() {  
        
        fetch('/api/choices' + '-' + {{question.id}}).then(function(response) { 
        response.json().then(function(data) {
        // console.log(data.correctText)
        let fc_1 = document.getElementById('fc-'+ '0')
        let fc_2 = document.getElementById('fc-'+ '1')
        let fc_3 = document.getElementById('fc-'+ '2')
        let fc_4 = document.getElementById('fc-'+ '3')

            let fcList = [fc_1, fc_2, fc_3, fc_4]
        
        for (let i = 0; i < 4; i++) {
            fcList[i].innerHTML = data.choices[i]
            if (data.choices[i] === data.correctText) {
                fcList[i].classList.add("correct-answer")
            }
        }

        })
    });

    fetch('/api/topic/' + {{question.topic_no}}).then(function(response) { 
        response.json().then(function(data) {
            document.getElementById('topic-header').innerHTML = data.name
        })
    });

    let isEditing = {{tempRemove}}
    if (isEditing !== 0) {
        document.getElementById('comment-box').innerText = document.getElementById('editComment').innerText
       
    }

    let btnDelete = document.getElementsByClassName('btnDelete')

    let i = 0;
    for (i = 0; i < btnDelete.length; i++) {
        btnDelete[i].addEventListener("click", (e) => {
            // console.log(e.target.value)
            document.getElementById('modalDeleteForm').action = "/discussion/" + {{question.id}} + "/delete/" + e.target.value
        })
    }

    
}, false);
})();


</script>


{% endblock scripts %}